---
services:
  pihole:
    container_name: pihole
    restart: ${RESTART_POLICY}
    env_file: .env
    image: pihole/pihole:latest
    networks:
      - default-main
    ports:
      - ${PIHOLE_DNS_PORT}:53/tcp
      - ${PIHOLE_DNS_PORT}:53/udp
      - ${PIHOLE_UI_PORT}:80/tcp
    environment:
      TZ: ${TIME_ZONE}
    volumes:
      - ${PIHOLE_CONFIG_VOLUME}:/etc/pihole
      - ${PIHOLE_DNS_VOLUME}:/etc/dnsmasq.d

networks:
  default-main:
    external: true
