---
services:
  nginx:
    image: 'jc21/nginx-proxy-manager:latest'
    env_file: .env
    container_name: nginx-proxy
    restart: ${RESTART_POLICY}
    ports:
      - ${NGINX_UI_PORT}:80
      - ${NGINX_HTTP_PORT}:443
      - ${NGINX_HTTPS_PORT}:81
    environment:
      # DB_SQLITE_FILE: ${NGINX_SQLLITE_DATA_FILE} # Uncomment this if you want to use sqlite
      DISABLE_IPV6: 'true'
      TZ: ${TIME_ZONE}
    volumes:
      - ${NGINX_DATA_VOLUME}:/data
      - ${NGINX_LETSENCRYPT_VOLUME}:/etc/letsencrypt
    networks:
      - default-main

networks:
  default-main:
    external: true