---
services:
  mssql:
    env_file: .env
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: Microsoft-SQL-2022
    networks:
      - default-main
    ports:
      - ${MSSQL_PORT}:1433
    volumes: 
      - ${MSSQL_DATA_VOLUME}:/docker
    environment:
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
      ACCEPT_EULA: ${ACCEPT_EULA}
      MSSQL_PID: ${MSSQL_PID}
      MSSQL_RPC_PORT: ${MSSQL_RPC_PORT}
      TZ: ${TIME_ZONE}
    restart: ${RESTART_POLICY}

networks:
  default-main:
    external: true